spring:
  datasource:
    url: jdbc:postgresql://postgres-shipping:5432/shippingdb
    driver-class-name: org.postgresql.Driver
    username: shippinguser
    password: shippingpass
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: false
