spring:
  datasource:
    url: jdbc:postgresql://postgres-payment:5432/paymentdb
    driver-class-name: org.postgresql.Driver
    username: paymentuser
    password: paymentpass
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: false
