spring:
  datasource:
    url: jdbc:postgresql://postgres-order:5432/orderdb
    driver-class-name: org.postgresql.Driver
    username: orderuser
    password: orderpass
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: false
