spring:
  datasource:
    url: jdbc:postgresql://postgres-inventory:5432/inventorydb
    driver-class-name: org.postgresql.Driver
    username: inventoryuser
    password: inventorypass
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: false
